global:
  resolve_timeout: 5m

route:
  receiver: "telegram"
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token: ""
        chat_id: 
        message: '{{ template "telegram.default" . }}'

templates:
  - '/etc/alertmanager/*.tmpl'

